ADDR_LISTEN_DEF: ''
ADDR_SERV: addr_server
PORT_SERV: port_server
ADDR_DEF: 127.0.0.1
PORT_DEF: 7777
MAX_CONNECT: 6
MAX_MESSAGE_LEN_BYTE: 1024
ENCODING: utf-8
ACTION: action
TIME: time
USER_NAME: user
ACCOUNT_NAME: account_name
PRESENCE: presence
RESPONSE: response
ERROR: error